<a href="https://colab.research.google.com/github/Jupiterian/ML-Learning-Portfolio/blob/main/Linear%20Algebra/GaussianElimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gaussian Elimination
The following contains work to show my Gaussian Elimination practice problems.

## Problem 1 (Source: Introduction to Linear Algebra Fourth Edition by Gilbert Strang)
Look for a matrix that has row sums 4 and 8, and column sums 2 and $s$:

$$\text{Matrix} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$$

$$a + b = 4 \qquad a + c = 2$$
$$c + d = 8 \qquad b + d = s$$

The four equations are solvable only if $s =$ \_\_\_\_. Then find two different matrices that have the correct row and column sums.

**Extra credit:** Write down the 4 by 4 system $Ax = b$ with $x = (a, b, c, d)$ and make $A$ triangular by elimination.

## Manual Solution
$$ a + b + c + d = 12 $$
$$ b + d = 10 $$
Thus, we get $$s = b + d = 10$$
Two possible matricies that satisfy the given conditions are (via trial and error).
$$\begin{bmatrix} 2 & 2 \\ 0 & 8 \end{bmatrix}$$
$$\begin{bmatrix} 3 & 1 \\ -1 & 9 \end{bmatrix}$$

Using the equation $$ A * (a, b, c, d) = (4, 2, 8, 10) $$, we can use our matrix multiplication rules to solve for A as
$$\text{A} = \begin{bmatrix} 1 & 1 & 0 & 0 \\ 1 & 0 & 1 & 0 \\ 0 & 0 & 1 & 1 \\ 0 & 1 & 0 & 1 \end{bmatrix}$$

We then apply Gaussian elimination steps to reduce matrix A to upper triangular form.
Here are the different matricies we get as we continue to operate on A:
$$\begin{bmatrix} 1 & 1 & 0 & 0 \\ 1 & 0 & 1 & 0 \\ 0 & 0 & 1 & 1 \\ 0 & 1 & 0 & 1 \end{bmatrix}$$
Subtracting the first row from the second row, we get$$\begin{bmatrix} 1 & 1 & 0 & 0 \\ 0 & -1 & 1 & 0 \\ 0 & 0 & 1 & 1 \\ 0 & 1 & 0 & 1 \end{bmatrix}$$.
Then, we perform a row swap:
$$\begin{bmatrix} 1 & 1 & 0 & 0 \\ 0 & -1 & 1 & 0 \\ 0 & 1 & 0 & 1 \\ 0 & 0 & 1 & 1 \end{bmatrix}$$
We then proceed to multiply the second row by -1 and then subtract it from the thrid row:
$$\begin{bmatrix} 1 & 1 & 0 & 0 \\ 0 & -1 & 1 & 0 \\ 0 & 0 & 1 & 1 \\ 0 & 0 & 1 & 1 \end{bmatrix}$$
Finally, we subtract the third row from the fourth row to get the matrix:
$$\begin{bmatrix} 1 & 1 & 0 & 0 \\ 0 & -1 & 1 & 0 \\ 0 & 0 & 1 & 1 \\ 0 & 0 & 0 & 0 \end{bmatrix}$$

Notice how this matrix is singular.

Below contains a code solution to evaluate the Gaussian Elimination on following matrix. The code does not rely upon any prebuilt numpy functions, only using numpy to define the matrix.

In [1]:
import numpy as np

A = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [0, 0, 1, 1], [0, 1, 0, 1]])
print(A)

[[1 1 0 0]
 [1 0 1 0]
 [0 0 1 1]
 [0 1 0 1]]
