<a href="https://colab.research.google.com/github/Jupiterian/ML-Learning-Portfolio/blob/main/Linear%20Algebra/Transposes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transposes
The following notebook contains sample exercepts of problems I have solved with transposes and their solutions. The main goal of this notebook, however is to create algorithms to calculate transposes of given matricies or vectors.

## Transpose Algorithms
Given a matrix $A$, return matrix $A^T$.

Solution 1 turns columns of $A$ into rows of $A^T$.
Solution 2 turns rows of $A$ into columns of $A^T$. Because numpy arrays are defined in terms of rows, a template matrix is created and then each element in each row is filled in this template matrix for Solution 2.

In [10]:
import numpy as np
def transposer(A):
  # Columns of A -> Rows of A^T

  ## Get matrix shape in numpy indicies
  rows = len(A)-1
  columns = len(A[1])-1

  A_transpose = []
  # Get columns and convert to rows
  for x in range (0, columns+1):
    column = A[:, x]
    A_transpose.append(column)

  return np.array(A_transpose)


# Test
matrix = np.random.random(size=[3, 3])
print(f"Matrix: {matrix}")
print(f"Tranpose: {transposer(matrix)}")

Matrix: [[0.67748922 0.83824324 0.49746856]
 [0.30763211 0.40084946 0.46655502]
 [0.21517016 0.75938192 0.10190622]]
Tranpose: [[0.67748922 0.30763211 0.21517016]
 [0.83824324 0.40084946 0.75938192]
 [0.49746856 0.46655502 0.10190622]]


In [19]:
# Note: Used small hint from AI to get the idea of zero matricies
import numpy as np
def transposer(A):
  # Columns of A -> Rows of A^T

  ## Get matrix shape in numpy indicies
  rows = len(A)-1
  columns = len(A[1])-1

  # Get columns and convert to rows
  zeroMatrix = np.random.random(size=[columns+1, rows+1])
  for y in range (0, rows+1):
    row = A[y, :]
    indicie = 0
    for x in row:
      zeroMatrix[indicie, y] = x
      indicie+=1

  return np.array(zeroMatrix)


# Test
matrix = np.random.random(size=[3, 3])
print(f"Matrix: {matrix}")
print(f"Tranpose: {transposer(matrix)}")

Matrix: [[0.58368325 0.51296354 0.11481538]
 [0.28654635 0.0642473  0.1615702 ]
 [0.48483862 0.84905631 0.58579743]]
Tranpose: [[0.58368325 0.28654635 0.48483862]
 [0.51296354 0.0642473  0.84905631]
 [0.11481538 0.1615702  0.58579743]]
