# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
randomTensor = torch.rand(7 , 7)
print(randomTensor)

tensor([[0.0515, 0.1781, 0.1841, 0.4865, 0.5401, 0.4257, 0.4269],
        [0.0133, 0.2042, 0.1176, 0.8097, 0.9490, 0.4339, 0.2560],
        [0.8678, 0.2724, 0.4612, 0.6353, 0.6807, 0.1128, 0.7345],
        [0.5031, 0.5485, 0.7839, 0.4979, 0.1623, 0.7132, 0.4905],
        [0.3353, 0.5312, 0.9115, 0.0711, 0.9271, 0.8496, 0.6705],
        [0.9828, 0.2646, 0.3731, 0.2765, 0.5814, 0.0679, 0.2940],
        [0.9422, 0.1956, 0.9345, 0.9339, 0.8703, 0.4069, 0.8300]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
randomTensor2 = torch.rand(1, 7)
randomTensor2 = randomTensor2.t()
# Perform matrix multiplication 
torch.matmul(randomTensor, randomTensor2)

tensor([[1.5293],
        [2.1036],
        [1.8193],
        [2.1991],
        [2.8346],
        [1.3334],
        [2.8879]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)
# Matrix multiply tensors
tensor2 = tensor2.t()
torch.matmul(tensor1, tensor2)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
cuda = torch.cuda.is_available()

# Create two random tensors on GPU
tensorX = torch.rand(2,3).cuda()
tensorY = torch.rand(2,3).cuda()
print(tensorX)
print(tensorY)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
tensorY = tensorY.t()
output = torch.mul(tensorX, tensorY)
print (output)

tensor([[0.0015, 0.1881, 0.1751],
        [0.1215, 0.0457, 0.3945]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print(torch.max(output))
# Find min
print(torch.min(output))

tensor(0.3945, device='cuda:0')
tensor(0.0015, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [15]:
# Find arg max
print(torch.amax(output))

# Find arg min
print(torch.amin(output))

tensor(0.3945, device='cuda:0')
tensor(0.0015, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [21]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed = torch.squeeze_copy(random)

# Print out tensors and their shapes
print(random) 
print(random.size())
print(squeezed)
print(squeezed.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
