# Day 1

In [4]:
import numpy as np

x = np.random.randn(1_000_000)

# Loop version
s = 0
#for i in range(len(x)):
    #s += x[i]
    #print(s)

# Vectorized version
s_vec = np.sum(x)
print(s_vec)

-992.0447922546181


## Exercise 1 Explanation
The foor loop version took about 22 seconds to run while the vectorized version ran almost immediately. This is because it performs operations on multiple elements at the same time.  

In [2]:
import numpy as np
x = np.array([1, 2, 3, 4])
print(x)
#Part 1: Convert to shape (4, 1)
x = x.reshape(4, 1)
print(x)
#Part 2: Convert to shape (1, 4)
x = x.reshape(1, 4)
print(x)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


The difference between shapes (4,) (4, 1) and (1, 4) is that 4 is just a single row of numbers, (4, 1) is a 4x1 matrix, while (1,4) is a 1x4 matrix. In a way, the outputs of (4,) and (1, 4) are similar.

In [12]:
import numpy as np

X = np.random.randn(5, 3)
mu = np.mean(X,axis=0)

print("X shape:", X.shape)
print("mu shape:", mu.shape)

Y = X - mu
print("Y shape:", Y.shape)


X shape: (5, 3)
mu shape: (3,)
Y shape: (5, 3)


Subtraction works in the first and third cases because the array can be scaled properly to match the shape of the X array. In cases 2 and 4, this is not possible and hence the Y = X - mu function does not work.

In [77]:
x = np.random.randn(10)
print(X.shape)
print(X)
mu = np.sum(x) / len(x)
var = np.sum((x-mu)**2)/ len(x)

print("manual mean:", mu)
print("manual var:", var)
print("numpy mean:", np.mean(x))
print("numpy var:", np.var(x))


(5, 3)
[[-1.03321156 -0.80043484  0.27601991]
 [ 0.55409778 -0.52118208 -0.31526263]
 [-1.73183297  0.12775074  1.30980699]
 [-0.4148845   2.09123362 -2.09499519]
 [-0.64183876 -0.22249868  0.93460321]]
manual mean: 0.35681628260450216
manual var: 1.5499744194019065
numpy mean: 0.35681628260450216
numpy var: 1.5499744194019065


NumPy will still work even if the shape changes of x changes. This is because mu is based on x.

The variance changes when the denominator changes because mu changes meaning the numerator changes the denominator changes as well. However, np.var(x) will still function normall, leading to a difference between those two.

The np.mean(x) and np.var(x) formulas are more stable.

In [88]:
x = np.random.randn(100) * 5 + 10
print(x)
z = (x - np.mean(x)) / np.std(x)
print(z)
print("mean after:", np.mean(z))
print("std after:", np.std(z))

[ 6.15752735  2.97772339  8.40681531 11.5328282   6.24226211  8.90629523
 12.97934072  6.35406795  8.75206045 18.21567897 -2.48828219  9.57521236
 10.82267555 23.78326229  5.47049625 14.58840322  4.91834055 10.52399408
 10.76016078  8.34181341  9.45876637  4.97669681  6.4503442  14.27603539
  0.55195898 13.80085664  5.71857992 12.1183211  13.17235531  6.11545879
  5.1685546   7.73738027  5.98742406  7.64764157 18.36894633  4.6050143
  7.86060162  4.28978418 12.74346479 17.83088718  8.4039208  12.77482196
 13.10507016  8.70502916  8.68494749 10.19384106  8.46063861 15.79254789
  5.77821627  8.25412242  8.43627058  8.09606879 14.55216131  6.22456239
 20.64270536  8.61656042 13.83375335  9.01282537 11.38933452 14.22951914
  5.73703442  1.57833563  5.87570551 15.98418936 11.89422729  1.61008753
 10.75205433 12.69719653 10.66368034  8.8037186  12.64146635 14.01167747
 15.10091579 11.01451561 10.88866047  9.70060107 16.97629139  5.3385352
 13.29545317  6.37074971 10.00590939 -2.87085855  8.6

I really don't know

In [94]:
X = np.random.randn(100, 4) * 10 + 5
mu = np.mean(X, axis=0)
z = (X-mu) / np.std(X, axis=0)
colWiseAvg = np.std(z, axis=0)
Y = X - mu
print(np.mean(z, axis=0))
print(np.std(z, axis=0))

[-1.14352972e-16 -4.71671313e-17  9.43689571e-17  1.83186799e-16]
[1. 1. 1. 1.]
