<a href="https://colab.research.google.com/github/Jupiterian/ML-Learning-Portfolio/blob/main/USAAIO%20Prep/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
# Exercise 1
def normalize(X):
  min = X.min(axis=0)
  max = X.max(axis=0)
  print(f"Min: {min}, Max: {max}")
  return (X-min) / (max-min)
test_array = np.random.randn(6,5)
print(test_array)
normalized = normalize(test_array)
print(f"Normalized: {normalized} with shape {normalized.shape}")

[[ 0.25368668  0.55426048 -1.13135398 -2.00036548 -0.52046164]
 [-1.55818045 -0.16227954 -1.719078    0.32114588 -0.06822168]
 [-0.78082783  0.0489962   0.99186323  0.89911389  0.44872127]
 [ 2.20880117  0.09810188 -0.44357666 -0.25057682 -0.12840135]
 [ 0.8512972   0.74006184  0.18878333 -0.05138885 -0.87461176]
 [ 0.13687138 -1.64119504  0.78631083 -0.24286318  0.83470082]]
Min: [-1.55818045 -1.64119504 -1.719078   -2.00036548 -0.87461176], Max: [2.20880117 0.74006184 0.99186323 0.89911389 0.83470082]
Normalized: [[0.48098645 0.92197341 0.21679703 0.         0.20718863]
 [0.         0.62106508 0.         0.8006649  0.4717628 ]
 [0.20635955 0.70978955 1.         1.         0.77419019]
 [1.         0.73041129 0.47050129 0.60348374 0.43655585]
 [0.63963085 1.         0.70376344 0.67218158 0.        ]
 [0.44997613 0.         0.92417674 0.60614409 1.        ]] with shape (6, 5)


In [31]:
# Exercise #2
def normVerifier(X_norm):
  min = X_norm.min(axis=0)
  max = X_norm.max(axis=0)
  for x in min:
    if not x>=0:
      return np.where(min == x)
    else:
      return None
  for x in max:
    if not x<=1:
      return np.where(max == x)
    else:
      return None
#Fail
print(normVerifier(test_array))
#Pass
print(normVerifier(normalized))

(array([0]),)
None


In [41]:
# Exercise #3
'''
Given X with shape (N, D):
Compute an (N, N) matrix where entry (i, j) is the Euclidean distance between X[i] and X[j].
Confirm:
The diagonal entries are all zero
The matrix is symmetric
No explicit loops

No scipy

Use broadcasting and matrix multiplication'''
X = np.random.rand(6, 5)
def edm(X):
  shape = X.shape
  N = shape[0]



[0.2447307  0.77921064 0.227981   0.47639959 0.00139197]
[[0.51621806 0.81857786 0.10602616 0.77747166 0.77913457]
 [0.2447307  0.77921064 0.227981   0.47639959 0.00139197]
 [0.46627062 0.4669234  0.72117711 0.10469025 0.70470005]
 [0.51273464 0.75189602 0.5596001  0.22428211 0.80818164]
 [0.68944245 0.30850824 0.87820372 0.7260942  0.36716062]
 [0.80379679 0.61842372 0.65855079 0.78705586 0.53722434]]
