<a href="https://colab.research.google.com/github/Jupiterian/ML-Learning-Portfolio/blob/main/USAAIO%20Prep/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
# Exercise 1
def normalize(X):
  min = X.min(axis=0)
  max = X.max(axis=0)
  print(f"Min: {min}, Max: {max}")
  return (X-min) / (max-min)
test_array = np.random.randn(6,5)
print(test_array)
normalized = normalize(test_array)
print(f"Normalized: {normalized} with shape {normalized.shape}")

[[ 0.85404353 -1.28024536 -1.77349901 -0.00230321  1.98453598]
 [-0.01686724  0.2481055   0.20588567  0.53784205  0.13561731]
 [-0.90706803  0.2268931  -1.00314655  0.46156626 -1.69017486]
 [-0.30619362 -2.02775704 -1.65268225  1.01197864 -0.31760923]
 [-0.60462379 -0.53043449 -0.11921472 -0.17110792 -0.42064771]
 [ 0.42166962  0.19500082  0.47081949  1.79584916  0.73654649]]
Min: [-0.90706803 -2.02775704 -1.77349901 -0.17110792 -1.69017486], Max: [0.85404353 0.2481055  0.47081949 1.79584916 1.98453598]
Normalized: [[1.         0.32845203 0.         0.08582023 1.        ]
 [0.50547666 1.         0.88195355 0.36042981 0.49685329]
 [0.         0.9906794  0.3432456  0.32165124 0.        ]
 [0.34119043 0.         0.05383227 0.60148062 0.37351664]
 [0.17173485 0.65791432 0.73709872 0.         0.34547675]
 [0.75448806 0.97666613 1.         1.         0.6603843 ]] with shape (6, 5)


In [5]:
# Exercise #2
def normVerifier(X_norm):
  min = X_norm.min(axis=0)
  max = X_norm.max(axis=0)
  for x in min:
    if not x>=0:
      return np.where(min == x)
    else:
      return None
  for x in max:
    if not x<=1:
      return np.where(max == x)
    else:
      return None
#Fail
print(normVerifier(test_array))
#Pass
print(normVerifier(normalized))

(array([0]),)
None


In [14]:
# Exercise #3
'''
Given X with shape (N, D):
Compute an (N, N) matrix where entry (i, j) is the Euclidean distance between X[i] and X[j].
Confirm:
The diagonal entries are all zero
The matrix is symmetric
No explicit loops

No scipy

Use broadcasting and matrix multiplication'''
X = np.random.rand(4, 2)
print(X)
def coolfunc(X):
  sq_norms = np.sum(X**2, axis=1, keepdims=True)
  print(f"square norms: {sq_norms}")
  dist_sq = sq_norms - 2 * X @ X.T + sq_norms.T
  print(f"distance norms: {dist_sq}")
  return np.sqrt(dist_sq)

print(coolfunc(X))

[[0.92582559 0.34447239]
 [0.69483853 0.81241055]
 [0.03776013 0.29449061]
 [0.32245284 0.52487677]]
square norms: [[0.97581425]
 [1.14281149]
 [0.08815055]
 [0.37947146]]
distance norms: [[0.         0.27232115 0.79115843 0.39660441]
 [0.27232115 0.         0.69999309 0.22134678]
 [0.79115843 0.69999309 0.         0.13412772]
 [0.39660441 0.22134678 0.13412772 0.        ]]
[[0.         0.52184399 0.88947087 0.62976536]
 [0.52184399 0.         0.83665589 0.47047505]
 [0.88947087 0.83665589 0.         0.36623452]
 [0.62976536 0.47047505 0.36623452 0.        ]]


 Note: come back to this exercise later

In [ ]:
# Exercise 4: k nearnest neighbors
def nearest_neighbors(array):
